import {
  Organization,
  Customer,
  Vendor,
  Invoice,
  Expense,
  Payment,
  RecurringInvoice,
  ActivityLog,
  OrganizationMember,
} from '../types/index.ts';

export function getSampleSeedData(orgId: string, userId: string, userEmail: string) {
  const now = new Date();
  const formatDate = (daysOffset: number) => {
    const d = new Date(now);
    d.setDate(d.getDate() + daysOffset);
    return d.toISOString().split('T')[0];
  };

  const sampleOrg: Organization = {
    id: orgId,
    name: 'Apex Cloud Solutions Inc.',
    slug: 'apex-cloud',
    currency: 'USD',
    paymentTermsDays: 30,
    email: 'billing@apexcloud.io',
    phone: '+1 (555) 234-8901',
    address: '100 Innovation Way, Suite 400',
    city: 'San Francisco',
    state: 'CA',
    postalCode: '94107',
    country: 'United States',
    taxId: 'US-94-3829104',
    website: 'https://apexcloud.example.com',
    invoiceNotes: 'Thank you for choosing Apex Cloud Solutions for your cloud infrastructure needs.',
    invoiceTerms: 'Payment due within 30 days. Late balances are subject to a 1.5% monthly charge.',
    createdBy: userId,
    createdAt: formatDate(-90),
  };

  const sampleMembers: OrganizationMember[] = [
    {
      id: `${orgId}_owner`,
      orgId,
      userId,
      userEmail,
      userName: userEmail.split('@')[0],
      role: 'owner',
      joinedAt: formatDate(-90),
    },
    {
      id: `${orgId}_m2`,
      orgId,
      userId: 'usr_sarah_cfo',
      userEmail: 'sarah.cfo@apexcloud.io',
      userName: 'Sarah Jenkins',
      role: 'accountant',
      joinedAt: formatDate(-60),
    },
    {
      id: `${orgId}_m3`,
      orgId,
      userId: 'usr_david_dev',
      userEmail: 'david.lead@apexcloud.io',
      userName: 'David Miller',
      role: 'staff',
      joinedAt: formatDate(-30),
    },
  ];

  const sampleCustomers: Customer[] = [
    {
      id: 'cust_1',
      orgId,
      name: 'Starlight Media Group',
      company: 'Starlight Media Inc.',
      email: 'accounts@starlightmedia.com',
      phone: '+1 (415) 890-1234',
      taxId: 'US-12-9847120',
      currency: 'USD',
      paymentTermsDays: 30,
      billingAddress: '742 Evergreen Terrace, Springfield, OR 97477',
      notes: 'Strategic enterprise client on annual retainer',
      outstandingBalance: 4200,
      totalInvoiced: 16800,
      totalPaid: 12600,
      createdAt: formatDate(-75),
    },
    {
      id: 'cust_2',
      orgId,
      name: 'Nexus Dynamics',
      company: 'Nexus Dynamics LLC',
      email: 'billing@nexusdynamics.io',
      phone: '+1 (650) 456-7890',
      taxId: 'US-88-1290384',
      currency: 'USD',
      paymentTermsDays: 15,
      billingAddress: '450 Mission St, 12th Floor, San Francisco, CA 94105',
      notes: 'B2B SaaS integration client',
      outstandingBalance: 0,
      totalInvoiced: 9500,
      totalPaid: 9500,
      createdAt: formatDate(-60),
    },
    {
      id: 'cust_3',
      orgId,
      name: 'Horizon Health Systems',
      company: 'Horizon Health Corp.',
      email: 'finance@horizonhealth.org',
      phone: '+1 (206) 789-0123',
      taxId: 'US-45-7819230',
      currency: 'USD',
      paymentTermsDays: 45,
      billingAddress: '1200 4th Ave, Seattle, WA 98101',
      notes: 'Healthcare compliance audit client - net 45',
      outstandingBalance: 6850,
      totalInvoiced: 6850,
      totalPaid: 0,
      createdAt: formatDate(-40),
    },
    {
      id: 'cust_4',
      orgId,
      name: 'Velocita Labs',
      company: 'Velocita AI Labs',
      email: 'pay@velocitalabs.ai',
      phone: '+1 (617) 345-6789',
      taxId: 'US-33-9182374',
      currency: 'USD',
      paymentTermsDays: 30,
      billingAddress: '500 Technology Square, Cambridge, MA 02139',
      notes: 'AI development partnership',
      outstandingBalance: 1500,
      totalInvoiced: 4500,
      totalPaid: 3000,
      createdAt: formatDate(-30),
    },
  ];

  const sampleVendors: Vendor[] = [
    {
      id: 'vend_1',
      orgId,
      name: 'Amazon Web Services',
      company: 'AWS Cloud Services',
      email: 'aws-receivables@amazon.com',
      phone: '+1 (800) 282-4467',
      taxId: 'US-91-1646860',
      category: 'software',
      address: '410 Terry Ave N, Seattle, WA 98109',
      notes: 'Primary cloud hosting and database cluster',
      totalExpenses: 4890,
      createdAt: formatDate(-90),
    },
    {
      id: 'vend_2',
      orgId,
      name: 'WeWork Labs',
      company: 'WeWork Companies LLC',
      email: 'billing@wework.com',
      phone: '+1 (646) 389-3922',
      taxId: 'US-82-0192834',
      category: 'office',
      address: '500 Howard St, San Francisco, CA 94105',
      notes: 'Dedicated office suites & meeting rooms',
      totalExpenses: 3200,
      createdAt: formatDate(-80),
    },
    {
      id: 'vend_3',
      orgId,
      name: 'GitHub Enterprise',
      company: 'GitHub Inc.',
      email: 'billing@github.com',
      phone: '+1 (877) 448-4820',
      taxId: 'US-26-8912340',
      category: 'software',
      address: '88 Colin P Kelly Jr St, San Francisco, CA 94107',
      notes: 'Code hosting, CI/CD Actions, and Copilot licenses',
      totalExpenses: 780,
      createdAt: formatDate(-70),
    },
    {
      id: 'vend_4',
      orgId,
      name: 'Delta Air Lines',
      company: 'Delta Air Lines Inc.',
      email: 'receipts@delta.com',
      phone: '+1 (800) 221-1212',
      taxId: 'US-58-0218548',
      category: 'travel',
      address: 'Atlanta, GA',
      notes: 'Client onsite travel and conferences',
      totalExpenses: 1420,
      createdAt: formatDate(-50),
    },
  ];

  const sampleInvoices: Invoice[] = [
    {
      id: 'inv_101',
      orgId,
      invoiceNumber: 'INV-2026-001',
      customerId: 'cust_1',
      customerName: 'Starlight Media Group',
      customerEmail: 'accounts@starlightmedia.com',
      issueDate: formatDate(-60),
      dueDate: formatDate(-30),
      status: 'paid',
      currency: 'USD',
      subtotal: 12000,
      discountPercent: 5,
      discountAmount: 600,
      taxPercent: 10,
      taxAmount: 1140,
      totalAmount: 12540,
      paidAmount: 12540,
      balanceDue: 0,
      notes: 'Phase 1 Cloud Architecture Implementation',
      terms: 'Net 30 days',
      items: [
        {
          id: 'item_1',
          description: 'Cloud Infrastructure Architecture & Terraform Provisioning',
          quantity: 60,
          unitPrice: 150,
          taxRatePercent: 10,
          amount: 9000,
        },
        {
          id: 'item_2',
          description: 'High-Availability Database Clustering & Tuning',
          quantity: 20,
          unitPrice: 150,
          taxRatePercent: 10,
          amount: 3000,
        },
      ],
      createdAt: formatDate(-60),
      createdBy: userId,
    },
    {
      id: 'inv_102',
      orgId,
      invoiceNumber: 'INV-2026-002',
      customerId: 'cust_2',
      customerName: 'Nexus Dynamics',
      customerEmail: 'billing@nexusdynamics.io',
      issueDate: formatDate(-45),
      dueDate: formatDate(-30),
      status: 'paid',
      currency: 'USD',
      subtotal: 9000,
      discountPercent: 0,
      discountAmount: 0,
      taxPercent: 5.5,
      taxAmount: 495,
      totalAmount: 9495,
      paidAmount: 9495,
      balanceDue: 0,
      notes: 'API Gateway Integration and Performance Optimization',
      terms: 'Net 15 days',
      items: [
        {
          id: 'item_3',
          description: 'Custom REST API Gateway and Webhook Orchestration',
          quantity: 1,
          unitPrice: 7500,
          taxRatePercent: 5.5,
          amount: 7500,
        },
        {
          id: 'item_4',
          description: 'Security & Penetration Testing Remediation',
          quantity: 10,
          unitPrice: 150,
          taxRatePercent: 5.5,
          amount: 1500,
        },
      ],
      createdAt: formatDate(-45),
      createdBy: userId,
    },
    {
      id: 'inv_103',
      orgId,
      invoiceNumber: 'INV-2026-003',
      customerId: 'cust_1',
      customerName: 'Starlight Media Group',
      customerEmail: 'accounts@starlightmedia.com',
      issueDate: formatDate(-20),
      dueDate: formatDate(10),
      status: 'partially_paid',
      currency: 'USD',
      subtotal: 4000,
      discountPercent: 0,
      discountAmount: 0,
      taxPercent: 5,
      taxAmount: 200,
      totalAmount: 4200,
      paidAmount: 2000,
      balanceDue: 2200,
      notes: 'Monthly Dedicated DevOps Retainer - March',
      terms: 'Net 30 days',
      items: [
        {
          id: 'item_5',
          description: 'Monthly Dedicated 24/7 SRE & DevOps Support Retainer',
          quantity: 1,
          unitPrice: 4000,
          taxRatePercent: 5,
          amount: 4000,
        },
      ],
      createdAt: formatDate(-20),
      createdBy: userId,
    },
    {
      id: 'inv_104',
      orgId,
      invoiceNumber: 'INV-2026-004',
      customerId: 'cust_3',
      customerName: 'Horizon Health Systems',
      customerEmail: 'finance@horizonhealth.org',
      issueDate: formatDate(-35),
      dueDate: formatDate(-5),
      status: 'overdue',
      currency: 'USD',
      subtotal: 6500,
      discountPercent: 0,
      discountAmount: 0,
      taxPercent: 5,
      taxAmount: 325,
      totalAmount: 6825,
      paidAmount: 0,
      balanceDue: 6825,
      notes: 'HIPAA Cloud Security & Compliance Audit Report',
      terms: 'Net 30 days. Overdue notice sent.',
      items: [
        {
          id: 'item_6',
          description: 'HIPAA Security Posture Assessment and Infrastructure Audit',
          quantity: 1,
          unitPrice: 5000,
          taxRatePercent: 5,
          amount: 5000,
        },
        {
          id: 'item_7',
          description: 'Encryption Key Management System (KMS) Setup',
          quantity: 1,
          unitPrice: 1500,
          taxRatePercent: 5,
          amount: 1500,
        },
      ],
      createdAt: formatDate(-35),
      createdBy: userId,
    },
    {
      id: 'inv_105',
      orgId,
      invoiceNumber: 'INV-2026-005',
      customerId: 'cust_4',
      customerName: 'Velocita Labs',
      customerEmail: 'pay@velocitalabs.ai',
      issueDate: formatDate(-5),
      dueDate: formatDate(25),
      status: 'sent',
      currency: 'USD',
      subtotal: 4500,
      discountPercent: 0,
      discountAmount: 0,
      taxPercent: 0,
      taxAmount: 0,
      totalAmount: 4500,
      paidAmount: 0,
      balanceDue: 4500,
      notes: 'LLM Fine-Tuning Pipeline Setup',
      terms: 'Net 30 days',
      items: [
        {
          id: 'item_8',
          description: 'Distributed Model Training Pipeline Architecture',
          quantity: 1,
          unitPrice: 4500,
          taxRatePercent: 0,
          amount: 4500,
        },
      ],
      createdAt: formatDate(-5),
      createdBy: userId,
    },
    {
      id: 'inv_106',
      orgId,
      invoiceNumber: 'INV-2026-006',
      customerId: 'cust_2',
      customerName: 'Nexus Dynamics',
      customerEmail: 'billing@nexusdynamics.io',
      issueDate: formatDate(0),
      dueDate: formatDate(30),
      status: 'draft',
      currency: 'USD',
      subtotal: 3200,
      discountPercent: 10,
      discountAmount: 320,
      taxPercent: 5,
      taxAmount: 144,
      totalAmount: 3024,
      paidAmount: 0,
      balanceDue: 3024,
      notes: 'Q2 Performance Monitoring Service Proposal',
      terms: 'Net 30 days',
      items: [
        {
          id: 'item_9',
          description: 'Grafana & Prometheus Observability Dashboard Suite',
          quantity: 1,
          unitPrice: 3200,
          taxRatePercent: 5,
          amount: 3200,
        },
      ],
      createdAt: formatDate(0),
      createdBy: userId,
    },
  ];

  const samplePayments: Payment[] = [
    {
      id: 'pay_1',
      orgId,
      invoiceId: 'inv_101',
      invoiceNumber: 'INV-2026-001',
      customerId: 'cust_1',
      customerName: 'Starlight Media Group',
      amount: 12540,
      paymentDate: formatDate(-32),
      paymentMethod: 'bank_transfer',
      reference: 'ACH-WIRE-892104',
      notes: 'Full payment received via Chase Commercial Wire',
      createdAt: formatDate(-32),
      createdBy: userId,
    },
    {
      id: 'pay_2',
      orgId,
      invoiceId: 'inv_102',
      invoiceNumber: 'INV-2026-002',
      customerId: 'cust_2',
      customerName: 'Nexus Dynamics',
      amount: 9495,
      paymentDate: formatDate(-30),
      paymentMethod: 'credit_card',
      reference: 'STRIPE-TXN-49021',
      notes: 'Paid online via corporate Amex',
      createdAt: formatDate(-30),
      createdBy: userId,
    },
    {
      id: 'pay_3',
      orgId,
      invoiceId: 'inv_103',
      invoiceNumber: 'INV-2026-003',
      customerId: 'cust_1',
      customerName: 'Starlight Media Group',
      amount: 2000,
      paymentDate: formatDate(-10),
      paymentMethod: 'bank_transfer',
      reference: 'ACH-WIRE-901233',
      notes: 'Partial advance retainer payment',
      createdAt: formatDate(-10),
      createdBy: userId,
    },
  ];

  const sampleExpenses: Expense[] = [
    {
      id: 'exp_1',
      orgId,
      vendorId: 'vend_1',
      vendorName: 'Amazon Web Services',
      category: 'software',
      description: 'Production ECS clusters, RDS Multi-AZ, and S3 Storage',
      expenseDate: formatDate(-28),
      amount: 2450,
      taxAmount: 0,
      currency: 'USD',
      paymentMethod: 'credit_card',
      isReimbursable: false,
      status: 'approved',
      receiptUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=400&q=80',
      receiptName: 'AWS-Billing-Feb-2026.pdf',
      notes: 'Monthly infrastructure run-rate',
      isRecurring: true,
      recurringInterval: 'monthly',
      createdAt: formatDate(-28),
      createdBy: userId,
    },
    {
      id: 'exp_2',
      orgId,
      vendorId: 'vend_2',
      vendorName: 'WeWork Labs',
      category: 'office',
      description: 'Private office suite rental - 4 desks and meeting credits',
      expenseDate: formatDate(-25),
      amount: 1600,
      taxAmount: 0,
      currency: 'USD',
      paymentMethod: 'bank_transfer',
      isReimbursable: false,
      status: 'approved',
      receiptUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=400&q=80',
      receiptName: 'WeWork-Invoice-40291.pdf',
      isRecurring: true,
      recurringInterval: 'monthly',
      createdAt: formatDate(-25),
      createdBy: userId,
    },
    {
      id: 'exp_3',
      orgId,
      vendorId: 'vend_3',
      vendorName: 'GitHub Enterprise',
      category: 'software',
      description: 'Enterprise seats and Actions runner minutes',
      expenseDate: formatDate(-18),
      amount: 390,
      taxAmount: 0,
      currency: 'USD',
      paymentMethod: 'credit_card',
      isReimbursable: false,
      status: 'approved',
      receiptName: 'GitHub-Receipt-984.pdf',
      createdAt: formatDate(-18),
      createdBy: userId,
    },
    {
      id: 'exp_4',
      orgId,
      vendorId: 'vend_4',
      vendorName: 'Delta Air Lines',
      category: 'travel',
      description: 'Roundtrip flight SFO -> SEA for Horizon Health onsite review',
      expenseDate: formatDate(-12),
      amount: 680,
      taxAmount: 48,
      currency: 'USD',
      paymentMethod: 'credit_card',
      isReimbursable: true,
      status: 'approved',
      receiptUrl: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=400&q=80',
      receiptName: 'Delta-E-Ticket-8921.pdf',
      notes: 'Client onsite kickoff meeting',
      createdAt: formatDate(-12),
      createdBy: userId,
    },
    {
      id: 'exp_5',
      orgId,
      category: 'meals',
      description: 'Team quarterly engineering dinner at Wayfare Tavern',
      expenseDate: formatDate(-8),
      amount: 340,
      taxAmount: 28,
      currency: 'USD',
      paymentMethod: 'credit_card',
      isReimbursable: true,
      status: 'pending',
      receiptUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=400&q=80',
      receiptName: 'Dinner-Receipt.jpg',
      notes: 'Dinner with 4 team engineers',
      createdAt: formatDate(-8),
      createdBy: userId,
    },
    {
      id: 'exp_6',
      orgId,
      category: 'advertising',
      description: 'Google Search Ads campaign for B2B cloud migration landing page',
      expenseDate: formatDate(-4),
      amount: 850,
      taxAmount: 0,
      currency: 'USD',
      paymentMethod: 'credit_card',
      isReimbursable: false,
      status: 'approved',
      receiptName: 'GoogleAds-Statement.pdf',
      createdAt: formatDate(-4),
      createdBy: userId,
    },
  ];

  const sampleRecurring: RecurringInvoice[] = [
    {
      id: 'rec_1',
      orgId,
      templateInvoiceNumber: 'REC-DEV-001',
      customerId: 'cust_1',
      customerName: 'Starlight Media Group',
      frequency: 'monthly',
      nextRunDate: formatDate(10),
      lastRunDate: formatDate(-20),
      occurrences: 4,
      maxOccurrences: 12,
      status: 'active',
      currency: 'USD',
      totalAmount: 4200,
      subtotal: 4000,
      taxAmount: 200,
      discountAmount: 0,
      items: [
        {
          id: 'rec_item_1',
          description: 'Monthly Dedicated 24/7 SRE & DevOps Support Retainer',
          quantity: 1,
          unitPrice: 4000,
          taxRatePercent: 5,
          amount: 4000,
        },
      ],
      notes: 'Auto-generated monthly retainer invoice',
      terms: 'Net 30 days',
      createdAt: formatDate(-90),
    },
  ];

  const sampleActivity: ActivityLog[] = [
    {
      id: 'act_1',
      orgId,
      userId,
      userEmail,
      action: 'Created Invoice INV-2026-006',
      entityType: 'invoice',
      entityId: 'inv_106',
      details: 'Draft invoice for Nexus Dynamics ($3,024.00)',
      createdAt: formatDate(0),
    },
    {
      id: 'act_2',
      orgId,
      userId,
      userEmail,
      action: 'Submitted Expense for Approval',
      entityType: 'expense',
      entityId: 'exp_5',
      details: 'Team engineering dinner ($340.00)',
      createdAt: formatDate(-8),
    },
    {
      id: 'act_3',
      orgId,
      userId,
      userEmail,
      action: 'Recorded Payment for INV-2026-003',
      entityType: 'payment',
      entityId: 'pay_3',
      details: 'Partial payment of $2,000.00 from Starlight Media',
      createdAt: formatDate(-10),
    },
    {
      id: 'act_4',
      orgId,
      userId,
      userEmail,
      action: 'Created Recurring Schedule REC-DEV-001',
      entityType: 'invoice',
      entityId: 'rec_1',
      details: 'Monthly recurring retainer for $4,200.00',
      createdAt: formatDate(-90),
    },
  ];

  return {
    organization: sampleOrg,
    members: sampleMembers,
    customers: sampleCustomers,
    vendors: sampleVendors,
    invoices: sampleInvoices,
    payments: samplePayments,
    expenses: sampleExpenses,
    recurring: sampleRecurring,
    activity: sampleActivity,
  };
}
